before_script:
  ##
  ## Install ssh-agent if not already installed, it is required by Docker.
  ## (change apt-get to yum if you use an RPM-based image)
  ##
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ##
  ## Assuming you created the SSH_KNOWN_HOSTS variable, uncomment the
  ## following two lines.
  ##
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

  ##
  ## Optionally, if you will be using any Git commands, set the user name and
  ## and email.
  ##
  #- git config --global user.email "user@example.com"
  #- git config --global user.name "User name"

compile-cljs:
  stage: build
  before_script:
    # Lein installation
    - apt-get update -y
    - apt-get install default-jre -y
    - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    - chmod a+x lein
    - export LEIN_ROOT=1
    - PATH=$PATH:.
    - lein deps
    - gem install sass

  script:
    - WEBMAN_WEBSITE=iranclojure.ir lein clean
    - WEBMAN_WEBSITE=iranclojure.ir lein cljsbuild once min
    - mkdir resources/public/css
    - WEBMAN_WEBSITE=iranclojure.ir lein sass-compile
    - cp -r resources/public ./public

  artifacts:
    paths:
      - public
  only:
    - stable


deploy:
  stage: deploy
  script:
    - ls
    - ssh www@iranclojure.ir 'rm -rf /home/www/iranclojure.ir'
    - scp -r ./public www@iranclojure.ir:/home/www/iranclojure.ir
    - ssh www@iranclojure.ir 'sudo systemctl restart nginx.service'
  only:
    stable
